// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zskjnfcalgarngzqmdkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpza2puZmNhbGdhcm5nenFtZGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDE5NzIsImV4cCI6MjA2NjAxNzk3Mn0.YymcVm-UMktqlm_RVHBXMSRqAN9Ks--ynId6pQ34HMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);